name: Publish Python distributions to PyPI and TestPyPI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 0 * * SUN"

jobs:
  ci:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - 3.7
          - 3.8
          - 3.9
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{matrix.python-version}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/libraries/dlt/requirements.txt
          pip install -r src/libraries/data_quality_pipeline/requirements.txt
      - name: Build binary wheel and a source tarball for DLT
        run: python src/dlt/setup.py sdist
      - name: Build binary wheel and a source tarball for DQ Pipeline
        run: python src/data_quality_pipeline/setup.py sdist
      - name: Run unit tests
        run: python -m pytest 
